sonar.projectKey=dhepakk08_CarbonSense
sonar.organization=dhepakk08
sonar.host.url=https://sonarcloud.io
sonar.sources=Back-end,Front-end
sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/test_*.py
sonar.python.coverage.reportPaths=Back-end/coverage.xml
